name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci