name: Ci
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: load & cache
        id: cacheS
        uses: ./.github/actions/cached_dep/
        with:
          caching: 'false'
      - name: cached info
        run: echo "cached used?  > ${{steps.cacheS.outputs.cached-dep}}"    
      - name: Lint code
        run: npm run lint
